### ISSUE TITLE
Can't request game after another game failed

### ISSUE THREAD

**Issue by tessmichi** [dennisss/chess#58] opened 2016-02-08 23:21 UTC
Just like with issue "https://github.com/dennisss/chess/issues/52"

That issue has been fixed, but now here is what happens

Specific example:
Tess requested a game with Tedd
Tedd declined the game
Now when Tess OR Tedd tries to start a game with the other one, the loading screen comes up right away then goes away as if the other instantly declined it.

Setting to 1.0 release since it isn't time-sensitive to being done in the next few days.

**Comment by dmz38** [comment] 2016-02-11 02:55
Confirmed bug.  Assigning to Zach because then he can become familiar with the API.

**Comment by dmz38** [comment] 2016-03-06 19:28
Confirmed fix.  Issue closed.

**Closed by dmz38** 2016-03-06 19:28 UTC
Labels: bug
